'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6250")>  _
        Public Property oscPort() As Integer
            Get
                Return CType(Me("oscPort"),Integer)
            End Get
            Set
                Me("oscPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost")>  _
        Public Property defaultAcmpServer() As String
            Get
                Return CType(Me("defaultAcmpServer"),String)
            End Get
            Set
                Me("defaultAcmpServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5250")>  _
        Public Property deafaultAcmpPort() As Integer
            Get
                Return CType(Me("deafaultAcmpPort"),Integer)
            End Get
            Set
                Me("deafaultAcmpPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property loglevel() As Integer
            Get
                Return CType(Me("loglevel"),Integer)
            End Get
            Set
                Me("loglevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("log.txt")>  _
        Public Property logfile() As String
            Get
                Return CType(Me("logfile"),String)
            End Get
            Set
                Me("logfile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property frameTickInterval() As Integer
            Get
                Return CType(Me("frameTickInterval"),Integer)
            End Get
            Set
                Me("frameTickInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3000")>  _
        Public Property connectionTimeout() As Integer
            Get
                Return CType(Me("connectionTimeout"),Integer)
            End Get
            Set
                Me("connectionTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property reconnectTries() As Integer
            Get
                Return CType(Me("reconnectTries"),Integer)
            End Get
            Set
                Me("reconnectTries") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property reconnectTimout() As Integer
            Get
                Return CType(Me("reconnectTimout"),Integer)
            End Get
            Set
                Me("reconnectTimout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property strictVersionControl() As Boolean
            Get
                Return CType(Me("strictVersionControl"),Boolean)
            End Get
            Set
                Me("strictVersionControl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property logToFile() As Boolean
            Get
                Return CType(Me("logToFile"),Boolean)
            End Get
            Set
                Me("logToFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property logToConsole() As Boolean
            Get
                Return CType(Me("logToConsole"),Boolean)
            End Get
            Set
                Me("logToConsole") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7000")>  _
        Public Property logShowTime() As Integer
            Get
                Return CType(Me("logShowTime"),Integer)
            End Get
            Set
                Me("logShowTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property last_AcmpServer() As String
            Get
                Return CType(Me("last_AcmpServer"),String)
            End Get
            Set
                Me("last_AcmpServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property last_AcmpPort() As String
            Get
                Return CType(Me("last_AcmpPort"),String)
            End Get
            Set
                Me("last_AcmpPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property last_Library() As String
            Get
                Return CType(Me("last_Library"),String)
            End Get
            Set
                Me("last_Library") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property last_Playlist() As String
            Get
                Return CType(Me("last_Playlist"),String)
            End Get
            Set
                Me("last_Playlist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property rememberLibrary() As Boolean
            Get
                Return CType(Me("rememberLibrary"),Boolean)
            End Get
            Set
                Me("rememberLibrary") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property rememberPlaylist() As Boolean
            Get
                Return CType(Me("rememberPlaylist"),Boolean)
            End Get
            Set
                Me("rememberPlaylist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property logdir() As String
            Get
                Return CType(Me("logdir"),String)
            End Get
            Set
                Me("logdir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property libdir() As String
            Get
                Return CType(Me("libdir"),String)
            End Get
            Set
                Me("libdir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property playlistdir() As String
            Get
                Return CType(Me("playlistdir"),String)
            End Get
            Set
                Me("playlistdir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5000")>  _
        Public Property noWarnTime() As Integer
            Get
                Return CType(Me("noWarnTime"),Integer)
            End Get
            Set
                Me("noWarnTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property warnTime() As Integer
            Get
                Return CType(Me("warnTime"),Integer)
            End Get
            Set
                Me("warnTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property rememberConnection() As Boolean
            Get
                Return CType(Me("rememberConnection"),Boolean)
            End Get
            Set
                Me("rememberConnection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property last_WindowLocation() As Global.System.Drawing.Point
            Get
                Return CType(Me("last_WindowLocation"),Global.System.Drawing.Point)
            End Get
            Set
                Me("last_WindowLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Maximized")>  _
        Public Property last_WindowState() As Global.System.Windows.Forms.FormWindowState
            Get
                Return CType(Me("last_WindowState"),Global.System.Windows.Forms.FormWindowState)
            End Get
            Set
                Me("last_WindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1024, 600")>  _
        Public Property last_WindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("last_WindowSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("last_WindowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property last_PlaylistWidth() As Integer
            Get
                Return CType(Me("last_PlaylistWidth"),Integer)
            End Get
            Set
                Me("last_PlaylistWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property last_LibraryWidth() As Integer
            Get
                Return CType(Me("last_LibraryWidth"),Integer)
            End Get
            Set
                Me("last_LibraryWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property last_CGHeight() As Integer
            Get
                Return CType(Me("last_CGHeight"),Integer)
            End Get
            Set
                Me("last_CGHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property rememberLayout() As Boolean
            Get
                Return CType(Me("rememberLayout"),Boolean)
            End Get
            Set
                Me("rememberLayout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property disconnectAtTimeout() As Boolean
            Get
                Return CType(Me("disconnectAtTimeout"),Boolean)
            End Get
            Set
                Me("disconnectAtTimeout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property fillMediaInfoAtRefresh() As Boolean
            Get
                Return CType(Me("fillMediaInfoAtRefresh"),Boolean)
            End Get
            Set
                Me("fillMediaInfoAtRefresh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property fillThumbnailAtRefresh() As Boolean
            Get
                Return CType(Me("fillThumbnailAtRefresh"),Boolean)
            End Get
            Set
                Me("fillThumbnailAtRefresh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property maxLibraryViewItems() As Integer
            Get
                Return CType(Me("maxLibraryViewItems"),Integer)
            End Get
            Set
                Me("maxLibraryViewItems") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property autoReconnect() As Boolean
            Get
                Return CType(Me("autoReconnect"),Boolean)
            End Get
            Set
                Me("autoReconnect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property checkConnectionInterval() As Integer
            Get
                Return CType(Me("checkConnectionInterval"),Integer)
            End Get
            Set
                Me("checkConnectionInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("False")> _
        Public Property defaultPlaylistCollapsed() As Boolean
            Get
                Return CType(Me("defaultPlaylistCollapsed"), Boolean)
            End Get
            Set(value As Boolean)
                Me("defaultPlaylistCollapsed") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CasparsPlayoutClient.My.MySettings
            Get
                Return Global.CasparsPlayoutClient.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
